### ISSUE TITLE
installing on mac - appearing in my daw

### ISSUE THREAD

**Issue by Joeyheheha** [trummerschlunk/master_me#100]
Hi all, sorry in advance (i couldn't be tech savvy if my life depended on it) but im having an issue with the plug in appearing with my other plug ins. I installed the software fine but after restarting my logic there is no sign of it. Can someone help me out? How can i access it? Thanks a lot

**Comment by falkTX** [comment]
Logic only supports AU, which master_me is not available for (it "only" does CLAP, LV2, VST2 and VST3).

**Comment by Joeyheheha** [comment]
Oh ok, so there's no way for me to use it?

**Comment by trummerschlunk** [comment]
You could try a wrapper, like:
https://syntheway.com/VSTAU.htm

EDIT: I guess, this is not maintained anymore...

**Comment by Joeyheheha** [comment]
I don't think thats worked, thanks though. Is there anything else i could try? Are there any plans to make this compatible with logic?

**Comment by trummerschlunk** [comment]
With BlueCat's Patchwork, it works...
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/19374731/227279129-bc37d20e-72a1-4e19-85e3-1d8785b43fda.png">
