### ISSUE TITLE
Installing vst3 instructions - Cubase 

### ISSUE THREAD

**Issue by JimmyShrimp** [trummerschlunk/master_me#101]
Are there any installation instructions?

I have tried to place the vst3 file in the usual place on win64 that my cubase installation will search and nothing shows up.

**Comment by Earratik** [comment]
I was wondering the same thing... win64...Fl studio

**Comment by Earratik** [comment]
Just cut and paste dll file.

**Comment by JimmyShrimp** [comment]
Fantastic, placed the vst3 and dll in the Windows VST3 folder and Cubase found it.

Thanks
