### ISSUE TITLE
Increased CPU consumption given a zero input signal

### ISSUE THREAD

**Issue by ion1** [trummerschlunk/master_me#102]
While master_me is receiving a non-zero signal, the CPU load reported by Cantabile is about 5–7&nbsp;% with some spikes above 10&nbsp;%, and the Time Load (which [measures what percentage of the length of the audio buffer was spent processing it](https://www.cantabilesoftware.com/guides/understandingPerformanceMetrics) AFAIU) is around 55&nbsp;% with some spikes above 100&nbsp;%.

![A lower load while receiving a non-zero signal](https://user-images.githubusercontent.com/39660/229322836-f4a1d922-e725-46c3-b51f-1a0971daa1c2.png)

While it's receiving a zero signal, the CPU load goes up to 16–17&nbsp;% and the Time Load is consistently above 100&nbsp;%, which would result in a choppy signal if it wasn't silent.

![A higher load while receiving a zero signal](https://user-images.githubusercontent.com/39660/229322914-1bfba529-ad84-4a68-ae54-60279a2a34e6.png)

I'm also experiencing the same with master_me as a filter in OBS. With a non-zero input signal:

![A lower load while receiving a non-zero signal](https://user-images.githubusercontent.com/39660/229323041-00a29928-34c1-454d-a234-9cfb277900e4.png)

With a zero input signal:

![A higher load while receiving a zero signal](https://user-images.githubusercontent.com/39660/229323052-a11d9f82-a129-498e-89c7-737d3757c1ca.png)

I'm running the 64-bit version of master_me 1.1.0 on Windows 10; VST3 in Cantabile and VST2 in OBS.

**Comment by nofishonfriday** [comment]
Denormalization issue? (just guessing without having looked at the code...)

**Comment by trummerschlunk** [comment]
This is clearly outside my expertise.
@x42 @magnetophon @sletz any ideas?

**Comment by falkTX** [comment]
i have an idea for dealing with this, already have stuff in DPF to deal with denormals automatically. Let me quickly add this in and we generate a new build for testing..

**Comment by falkTX** [comment]
Pushed a fix in a4c1867bac814020cf12aa72f5fa27d92f0a1322

**Comment by sletz** [comment]
In Faust ecosystem we use code to activate Flush To Zero (FTZ) at CPU level, see: https://github.com/grame-cncm/faust/blob/master-dev/architecture/faust/dsp/dsp.h#L244

**Comment by falkTX** [comment]
The commit I pushed does the same, and reverting to the previous cpu flags at the end. (plus support for armhf, which faust does not have)

I really dislike this approach, even if necessary. Hosts should be the ones doing this, plugins messing up with global state is always a problem...

**Comment by sletz** [comment]
@falkTX  So testing each sample ? I don't understand what the code is actually doing.

**Comment by nofishonfriday** [comment]
> The commit I pushed does the same, and reverting to the previous cpu flags at the end. (plus support for armhf, which faust does not have)

Excuse me for hopping in from the side, just lurking and learning... :)
Shouldn't this
`if (!std::isfinite(inputs[0][i]))`
https://github.com/trummerschlunk/master_me/commit/a4c1867bac814020cf12aa72f5fa27d92f0a1322#diff-8fcc70059c29daa59cef018623a43f454a1e5bd2bee932dacfbabe28b946a457R198

rather be
 `if (!std::isfinite(inputs[1][i]))`

otherwise it'd do the first input twice, no?

**Comment by falkTX** [comment]
> > The commit I pushed does the same, and reverting to the previous cpu flags at the end. (plus support for armhf, which faust does not have)
> 
> Excuse me for hopping in from the side, just lurking and learning... :) Shouldn't this `if (!std::isfinite(inputs[0][i]))` [a4c1867#diff-8fcc70059c29daa59cef018623a43f454a1e5bd2bee932dacfbabe28b946a457R198](https://github.com/trummerschlunk/master_me/commit/a4c1867bac814020cf12aa72f5fa27d92f0a1322#diff-8fcc70059c29daa59cef018623a43f454a1e5bd2bee932dacfbabe28b946a457R198)
> 
> rather be `if (!std::isfinite(inputs[1][i]))`
> 
> otherwise it'd do the first input twice, no?

yes, fixed in the next commit.



> @falkTX So testing each sample ? I don't understand what the code is actually doing.

that is something separate, the FTZ stuff is handled by the class instance there. see https://github.com/DISTRHO/DPF/blob/develop/distrho/extra/ScopedDenormalDisable.hpp#L32

the "unreachable" code path is just so the compiler can optimize things a bit more, it is not what does the FTZ denormal handling.

**Comment by x42** [comment]
Since `isfinite` cannot be vectorized, it usually makes more sense to only sanitize internal state variables at the end of each process cycle.  While that approach still allows for garbage in, garbage out the DSP recovers.

**Comment by ion1** [comment]
I tested https://github.com/trummerschlunk/master_me/actions/runs/4595877825#artifacts and the change seems to have fixed the issue. The Time Load measure is now consistently around 30 % and CPU Load is around 5 % in Cantabile. Thank you!
