### ISSUE TITLE
Noob install help

### ISSUE THREAD

**Issue by Musicmonk84** [trummerschlunk/master_me#103]
Hi. I don't think I've ever used Github. Now I'm trying to install this cool plugin and I went through the normal install process and it seems the plugin is nowhere to be found. Yes I restarted my macbook.

Macbook Air 2020
Mac OS: Monterey 12.6
Pro Tools Version 2022.10.0

**Comment by falkTX** [comment]
master_me supports CLAP, LV2, VST2 and VST3 but not AU which is the only allowed plugin format in Pro Tools.
So you cant use it there for the moment.

**Comment by trummerschlunk** [comment]
You could use a wrapper.
I tested master_me in Blue Cat's Patchwork and it works. One person reported graphics problems though.
