### ISSUE TITLE
# Dowloaded plugin, but it is not showing up in Logic Pro

### ISSUE THREAD

**Issue by A1burt** [trummerschlunk/master_me#104]
Hello, I am not as tech savvy as a lot of you appear to be. I am just a sucker for a well reviewed mastering plugin.
Also new to GitHub so I am unaware of any formatting (please forgive).

So, I installed master_me. Restarted Mac many times(I have had to do in the past). No dice.

Checked my plugin manager under preferences/ settings. All other third party plugins have shown up, but not master_me. I reset and rescanned all plugins: Still not visible in the DAW.

Cleared cache. No avail.

Manually put the plugin components into the correct folders. It is still not appearing in logic.

Bear in mind I just updated to VentureOS 13.3
I only updated to troubleshoot.

Can someone guide me as to what I am doing wrong?

**Comment by trummerschlunk** [comment]
Hi :)

master_me is not compatible with apple's native AU plugin format. Therefore, it will not show in Logic.
There is a workaround using a 'wrapper' like Blue Cat's 'Patchwork'.

I will add a compatibility section to the readme clarifying this.

Hope you can test master_me soon :)

**Comment by falkTX** [comment]
The amount of people asking for AU is quite substantial...
I need to add support for it in DPF then, later in the year probably

**Comment by trummerschlunk** [comment]
Thanks to @falkTX there is an AU version now!
So far running smoothly on MacOS 12.6.4 MacBook Pro M1pro <3

Installer: https://github.com/trummerschlunk/master_me/suites/12168475357/artifacts/642290851

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/19374731/231426063-bab1fb1c-739f-45f3-9633-89356289a879.png">
