### ISSUE TITLE
dpf submodule use a commit that has vanished

### ISSUE THREAD

**Issue by hfiguiere** [trummerschlunk/master_me#108]
the dpf submodule is pinned to a commit that has vanished which make checkout fail in many cases.

![image](https://user-images.githubusercontent.com/114441/233803983-7d9ab00b-5ae8-459e-b96a-9443ec4cec66.png)

**Comment by falkTX** [comment]
that is because I force-pushed to refresh it, as it has AU stuff which relies on experimental stuff so it sits on a branch.
what issue does it make for you?

**Comment by hfiguiere** [comment]
that the commit can't be found.

**Comment by falkTX** [comment]
commit is always there, just without a reference to any active branch.
the link https://github.com/DISTRHO/DPF/tree/d9088872a3ee65d33c6b9a60222dc9364b22b81a still works.

is some build failing because of it?

for source builds there is a source tarball in the releases

**Comment by falkTX** [comment]
closing as it is a non-issue

**Comment by hfiguiere** [comment]
commit outside of branches are usually not fetched. This is how git works.
