### ISSUE TITLE
More a Feature request (sorry didn't know how to place it elsewhere): Spinoff the 8-band Compressor as plugin on it's own

### ISSUE THREAD

**Issue by huberp** [trummerschlunk/master_me#109]
I like the 8-band compressor and would like to have it as a individual module. And let me just add: I like the whole master_me  and used it even on my recent tracks with a bit less "aggressive" settings then the default. But it's cool to have it in the mastering chain. So I'd say it's not only usefull for podcasts.

The 8-band compressor spin off could add and option which allow users to go with a.) with the interpolated values you guys derive from the settings of lowest and highest band or b.) set a "choose individual settings manually" check box and then set them manually for each band ... probably with a button "reset to interpolated defaults" which then sets the values of the interpolated bands to have some values to start with.

Or why not do a simple 8-band splitter with individual DAW outs, that allows users to do what ever they want to do on the individual bands... a bit like ISOL8 hich is a very good 5-band splitter I use often. I could even think about choosing the filter poles and filter types (linear phase vs not linear phase) ...

Anyway ... just wanted to place my ideas somewhere. master_me is cool! Keep up the good work!

**Comment by trummerschlunk** [comment]
Hey @huberp !

Glad to hear that some of your tracks benefit from using - at least some parts of - master_me!

...because I do it too ;)

I am actually thinking about developing some plugins in the future, more aimed at a pro-audio audience. We'll see...

Cheers,
Klaus
