### ISSUE TITLE
Use `stdfaust.lib` for smoothing

### ISSUE THREAD

**Issue by jkbd** [trummerschlunk/master_me#12]
I think, `lp1p(cf)` is identical to `si.smooth(ba.tau2pole(foo))` with `foo = 1/(2*ma.PI*cf)`.

I looked at the C++-Code generated from
```
process = _ <: lp1p(cf), si.smooth(ba.tau2pole(1/(2*ma.PI*cf)))
with {
  cf = ma.E;
};
```
which yields
```
for (int i0 = 0; i0 < count; i0 = i0 + 1) {
	float fTemp0 = fConst1 * float(input0[i0]);

	fRec0[0] = fConst0 * fRec0[1] + fTemp0;
	output0[i0] = FAUSTFLOAT(fRec0[0]);
	fRec1[0] = fTemp0 + fConst0 * fRec1[1]; // summands swapped
	output1[i0] = FAUSTFLOAT(fRec1[0]);

	fRec0[1] = fRec0[0];
	fRec1[1] = fRec1[0];
}
```
I would prefer using the standard library. At first, `lp1p(cf)` made me think, "oh, super-elaborated ballistics going on".

**Comment by trummerschlunk** [comment]
Sure, the more standard, the better.
Tried it, works :)

Do you want to do a pr or shall I change it myself?

**Comment by jkbd** [comment]
If you have some time now, please go ahead.

**Comment by trummerschlunk** [comment]
done, thanks :)
