### ISSUE TITLE
one cpu at 100 % - other cpus are bored

### ISSUE THREAD

**Issue by SimpelMe** [trummerschlunk/master_me#122]
I'm trying to build an auto mixing setup for 38c3. I have 5 stages to handle with 3 to auto level sources each: foh, translation a and translation b. All those sources come not levelled well.

I currently use logic pro 11.0.1 as mixing daw. My machine is a mac mini m2 with 8 gb memory. When running my setup with 4 stages (12 master_me in total) at the latest, one processor is at 100 percent and adding another master_me will scramble audio. All the other processors are nearly bored.

Do you have any idea how to fix this?
Regards, Simpel

**Comment by magnetophon** [comment]
Happy to hear that our plugin is still used at ccc!
Hope I can make it again this year!
Got any room in the audio team?  (Been doing audio for 2 decades now).

I don't know the actual cause of the problem, maybe @falkTX knows.

I do know a possible solution: I could split the leveler into it's own plugin, which would be much lighter in resource usage.
Optionally I could also use my more advanced leveling algo, which was considered too heavy for an already heavy plugin, but which will still be much much lighter than the full plugin.

**Comment by magnetophon** [comment]
Heh, just noticed https://github.com/SimpelMe/voc-leveler.
Seems like you had the same idea 3 years ago.  :)

**Comment by SimpelMe** [comment]
It's somewhat evolution. 3 years ago the approach was cli based. Did not work as I wanted as I had to adapt parameters live.

Last year no idea didn't work at all. So I had four 16 hours shifts live mixing on a digital console. Will not repeat it this year.

This year it should be based on a stable daw only mixing and nothing more. (Backup recording should be done elsewhere.)

**Comment by SimpelMe** [comment]
> I do know a possible solution: I could split the leveler into it's own plugin, which would be much lighter in resource usage.

Will that be better than deactivating every module except the leveller in the plugin itself?

**Comment by magnetophon** [comment]
Yes, that will be much better.  
In faust you cannot really switch off processing, so it's always using a constant amount of CPU.
Which has advantages, cause if your cpu can handle the load now, it can handle the load at the end of that 16 hour shift as well (assuming no heat issues...)

Would you like me to whip something up?

**Comment by SimpelMe** [comment]
> Would you like me to whip something up?

Definitely! The leveller alone is what I exactly need. All other modules I switched off currently. "level_me" for the win.

**Comment by trummerschlunk** [comment]
nice @magnetophon !

@SimpelMe I guess you need an AU version then?

**Comment by SimpelMe** [comment]
Yes, currently with logic I need an AU version.

**Comment by trummerschlunk** [comment]
> Yes, currently with logic I need an AU version.

maybe @falkTX can help with that?
If not, I am currently working on an advanced leveler in plugdata which is available as AU. Should be ready soon-ish ;)

**Comment by magnetophon** [comment]
I could make a CLAP & VST3, would that work?
At least with a wrapper that should be OK, no?
This site suggests there is even native support for VST3 now, but most sites claim AU only, so I'm a bit confused.
https://www.charlescleyn.com/blog/how-to-add-vsts-in-logic-pro

**Comment by falkTX** [comment]
If we go with DPF we can support AU, since this is just faust you can just fork the repo at https://github.com/DISTRHO/Fadeli/ and get the macOS binaries from github artifacts.
I will update that right now to make sure AU format is enabled.

**Comment by magnetophon** [comment]
@falkTX  Thanks!
I had a bit of trouble actually getting it to build on macos:
https://github.com/magnetophon/leveler_dpf/actions/workflows/build.yml

@SimpelMe  Let us know if it works for you!
https://github.com/magnetophon/leveler_dpf/actions/runs/11703817511


PS: the faust version works, but I cannot easily test the DPF version, since I'm on NixOS, and faustpp hasn't been packaged yet.
While I've contributed many packages to NixOS, I have not figured out python packaging yet.

**Comment by SimpelMe** [comment]
YESSSSS! It works like charm (testing au). Processor 1 is under 50 percent with all needed levelers. That's exactly what I needed. I thank you very much. 

I close the issue because high cpu usage is handled in issue #66.
