### ISSUE TITLE
What is the target environment?

### ISSUE THREAD

**Issue by jkbd** [trummerschlunk/master_me#17]
In the best case, this software runs everywhere and shines with all the platform dependent details. Sure, beauty is our business.
But what is the **most important niche**, where it has to run properly as soon as possible? That is:

- Operating System
- Plug-in host or interface
- GUI related environment

**Comment by trummerschlunk** [comment]
I guess plugins are the most important. Users will probably use OBS or Reaper or thelike and just throw it on the master bus.

my partner's dad wants it in his hearing aids ;)
Which is a brilliant idea... actually I am talking to a person who develops for open source hearing aids.

**Comment by magnetophon** [comment]
> my partner's dad wants it in his hearing aids ;)

My dad doesn't yet know he wants it, but he always tells me the soft sounds are ok and loud sounds are too loud.

> Which is a brilliant idea... actually I am talking to a person who develops for open source hearing aids.

Do you know what kind of dynamics processing is standard in modern hearing aids?
Single band? Multi band? Separate limiter and compressor?
Do you have any idea about the amount of cpu available?

**Comment by trummerschlunk** [comment]
No, I did not investigate yet due to lack of time. But the idea of having a 'little mastering engineer' in his ears totally sells it to him.

Next project. You in? ;)

**Comment by jkbd** [comment]
My neighbor controls his "ears" with an app. I think, some DSP processing-power is available but most parameters are hidden from the user by using "profiles". I can try to get some details from a hearing aids service person next week.

**Comment by magnetophon** [comment]
> Next project. You in? ;)

Absolutely! I'd love to gift my dad better hearing!

>  I can try to get some details from a hearing aids service person next week.

Please do!

**Comment by jkbd** [comment]
Okay, [Open Broadcaster Software (OBS)](https://obsproject.com/) was mentioned. On Linux it can get an audio stream from ALSA, [JACK](https://jackaudio.org/) or Sndio. It has options for "Audiofilter"s but cannot load LV2, CLAP or VST plug-ins.
Given all that, I would prefer to run a JACK server. The smallest setup then would be Soundsgood as a JACK client, OBS and maybe some aid for port connection.
Any comments? What would be the easiest setup on Windows or macOS?

**Comment by trummerschlunk** [comment]
There is an OBS linux version which supports lv2, but it's extremely buggy and never worked for me.
A jack app is definitely needed.

**Comment by jkbd** [comment]
One can use [Reaper](https://www.reaper.fm/index.php) for streaming audio? Quick search did not provide information to me.

I remember, [Mixxx](https://mixxx.org/) can broadcast to [Shoutcast](https://www.shoutcast.com/) or [Icecast](https://icecast.org/). I only found a changelog that LV2 plug-ins can be loaded, but not their GUI.

I used [Darkice](http://www.darkice.org/) and JACK before, to stream audio to Icecast. But again, I thought, we are trying to provide the non-techies with a simple and robust solution. Managing JACK-connections is already advanced stuff in my opinion.

**Comment by trummerschlunk** [comment]
Reaper: well not directly, I guess. But also podcasters are a potential target group.

OBS on linux. I think, when one is streaming via obs on linux, they will probably familiar with jack.
OBS on mac & win: vst. (the only weird thing about OBS is that the mixer has no master bus...)

For the voc team it will be a GUI-less linux LV2 plugin in their ffmpeg chain.

Chris Chafe would like to include soundsgood as a clickable option in jacktrip. He only needs the faust dsp file.

**Comment by sletz** [comment]
Using Faust for hearing aids? Nice project, I will follow ((-;

**Comment by x42** [comment]
> actually I am talking to a person who develops for open source hearing aids.

[openMHA](https://github.com/HoerTech-gGmbH/openMHA) ? Giso Grimm?  He regularly presented it at the Linux Audio Conference, and he's also active on the LAD, LAU user lists.

**Comment by jkbd** [comment]
Conclusion so far:

- [X] raw FAUST-DSP code. E.g. for [JackTrip](https://www.jacktrip.com/).
- [X] LV2 plug-in without GUI. E.g. for use with [FFmpeg](https://ffmpeg.org/).
- [ ] JACK client with GUI on Linux. E.g. needed for Darkice or OBS. The meters in the GUI shall be with a meaningful scale and independent from block size.
- [ ] Something to use in other cases, maybe.
