### ISSUE TITLE
Feature request: expose crossover frequencies.

### ISSUE THREAD

**Issue by magnetophon** [trummerschlunk/master_me#19]
IMHO, anybody who can handle the "expert" interface, will welcome being able to tweak the crossover frequencies.
``` faust
crossoverFreqs = vslider("v:soundsgood/t:expert/h:[5]mscomp/h:[1]low band/[1]mscomp low freq", 60, 20, 20000, 1),vslider("v:soundsgood/t:expert/h:[5]mscomp/h:[2]high band/[1]mscomp high freq", 8000, 20, 20000, 1):LogArray(Nr_crossoverFreqs);
```

**Comment by trummerschlunk** [comment]
this will specify first and last crossover frequency of the 8 frequency bands, right?
I hardcoded it because I think it should be evenly spread throughout the spectrum. Does it make sense any other way?

**Comment by magnetophon** [comment]
> this will specify first and last crossover frequency of the 8 frequency bands, right?

Yes, and the other frequencies will be evenly (so in this case logarithmicly) spaced between them. 

> I hardcoded it because I think it should be evenly spread throughout the spectrum. Does it make sense any other way?

I've been testing a lot with musical content, and especially there, it's nice to tweak these.
When you have a very Sub-bass heavy song, it's nice to lower the freq a bit, so the sub and the kick bass get separate GR.
When you have a song from the 50's or 60's without any sub, it's nice to make the freq a bit higher, again, so that the bass energy gets divided over 2 bands.

Try it, I found it very satisfying to use these parameters.

What is the downside of exposing them?

**Comment by trummerschlunk** [comment]
I hear you. I'll put them back ;)
Downside: a very hard to understand parameter, when you are not an expert.
But that is probably true for the whole multiband ms compressor ;)

**Comment by trummerschlunk** [comment]
done.
funny pitch effects here when changing frequencies fast ;)
