### ISSUE TITLE
Bypass might cause clicks

### ISSUE THREAD

**Issue by jkbd** [trummerschlunk/master_me#2]
I think, the bypass of `correlate_correct_bp` ([line 251](https://github.com/jkbd/soundsgood/blob/cc132ecabddfc99e83ed1ab2a0c4fced017a582f/soundsgood.dsp#L251))might cause audible clicks, because it uses `select2` for the audio signal.

**Comment by trummerschlunk** [comment]
I experienced some strange behavior with ba.bypass anyway. It cuts the audio input of the bypassed process. Whereas I need a dry output sometimes while the process is still doing it's thing.

**Comment by trummerschlunk** [comment]
Solved by new bypass function bp2
