### ISSUE TITLE
giving names and symbols to compressor gain reduction controls

### ISSUE THREAD

**Issue by falkTX** [trummerschlunk/master_me#22]
There is commented code around the compressor gain reduction naming part:

```
  //meter(i) = _<:(_, (ba.linear2db:max(-40):min(0):vbargraph("v:soundsgood/t:expert/h:[6]mscomp_meter/[%i][unit:dB]%i[tooltip: gain reduction in dB]", -3, 0))):attach;
  meter(i) = _<:(_, (ba.linear2db:max(-40):min(0):vbargraph("v:soundsgood/t:expert/h:[6]mscomp_meter/[%i][unit:dB][tooltip: gain reduction in dB]", -3, 0))):attach;
```

From what I could understand, these are dynamic stereo controls, so giving a name makes it appear duplicate.

I guess it is commented out until a solution is found.
This ticket can serve as a reminder, as we need this for the plugin version too.

**Comment by sletz** [comment]
The [2.41.1 Faust release](https://github.com/grame-cncm/faust/releases) has: 
- Relax same path rule causing errors for bargraph.

**Comment by trummerschlunk** [comment]
Yes, @falkTX, with the commented line, the code did not compile on your end, so I got rid of the `%i`, because both meters for each band are given the same name.

Any ideas how to solve this?

**Comment by falkTX** [comment]
that is exactly my question, I dont know how to solve it either.
is there an extra % param faust sets that expands to the L vs R channel?

**Comment by x42** [comment]
Since  ea35b398, there is `meter(b,c)` band/channel are separate and the port symbols is `msredux%b%c`.
Upstream faust now allows to format `%{b}_%{c}` as well.

This issue can be closed.

**Comment by falkTX** [comment]
there are still the names of the kneecomp meters, those dont have symbols or names altogether yet

**Comment by trummerschlunk** [comment]
Solved.
