### ISSUE TITLE
GUI: ideas and sketches

### ISSUE THREAD

**Issue by trummerschlunk** [trummerschlunk/master_me#23]
so this is how it will probably look like. Not the comic style though ;)
![soundsgood gui sketch easy 01 excalidraw](https://user-images.githubusercontent.com/19374731/184860042-f266bceb-8091-4683-99d7-89b8f5f4aad4.svg)

![soundsgood gui sketch expert 01 excalidraw](https://user-images.githubusercontent.com/19374731/184860252-70f380af-1a56-4dab-9d59-ec11fb4c5707.svg)

**Comment by magnetophon** [comment]
Looks great.

In the current faust generated gui, I am missing the spatial relation of the MB compressor.
The above configuration is the only one that makes sense: low bands left, high bands right, matching parameters next to each other.
That is how I [originally](https://github.com/magnetophon/faustExperiments/blob/master/N_band_Compressor_N_chan.dsp) wrote it.

**Comment by magnetophon** [comment]
Where will you display the GR?
I find it invaluable to see all the meters as I tweak, since most controls affect all meters: when you do less GR in one compressor, the others will often have to do more, and vise versa.

**Comment by trummerschlunk** [comment]
I was just too lazy for the meters yet. They will be in the corresponding block.

**Comment by trummerschlunk** [comment]
![soundsgood gui sketch expert04 excalidraw](https://user-images.githubusercontent.com/19374731/185084674-89e46264-a0d6-42a5-8896-b029141b0111.svg)


It's a lot of parameters, but I guess this way it could fit.
With the colors, I am not quite sure yet.

How do you like it?

**Comment by falkTX** [comment]
fitting everything is a single view is nice, though it does get quite compact then.
what about arrows to indicate the flow/order of the processing?

perhaps better to have the sliders and widget controls on the left, and labels on the right. it is more commonplace for it to be like that.

**Comment by trummerschlunk** [comment]
![soundsgood gui sketch expert05 excalidraw](https://user-images.githubusercontent.com/19374731/185088350-8b3b636a-723e-4559-96ee-ba4b874940dc.svg)

Arrows are nice.

**Comment by trummerschlunk** [comment]
yeah, labels on the right of sliders might be nice

**Comment by magnetophon** [comment]
> fitting everything is a single view is nice, though it does get quite compact then.

You could save some space in the MB-comp by using just one label, in the middle of the two sliders.

**Comment by trummerschlunk** [comment]
I am really worried if this is getting too big for one page. It would be awesome.

Please let me know if it does not work...

**Comment by trummerschlunk** [comment]
> > fitting everything is a single view is nice, though it does get quite compact then.
> 
> You could save some space in the MB-comp by using just one label, in the middle of the two sliders.

good idea!

**Comment by trummerschlunk** [comment]
I forgot: the sliders should be double-clickable to enter precise values.

**Comment by magnetophon** [comment]
Also, we can save some space by:

- Making the name smaller
- making the big meters less wide
- making the presets into a dropdown
- arranging the name, the presets and easy/expert all on one pane, so less empty space

**Comment by trummerschlunk** [comment]
how do you like the big 'easy' components?

**Comment by trummerschlunk** [comment]
![soundsgood gui sketch expert06 excalidraw](https://user-images.githubusercontent.com/19374731/185091652-84299122-a4ac-45ac-90e7-a27008f46589.svg)

**Comment by magnetophon** [comment]
A more general question:  it seems to me the DSP is not finished yet; you still need to decide wich blocks will be in the final product, and which parameters of wich blocks are exposed (for example, I would expose the knee parameter of all compressors and limiters.

Finally, also related to how the gui will look, sice it depicts the flow: shouldn't the correlation correction be after all the MS processing?
Maybe I misunderstood what it's supposed to do, but from the name and a quick glance at the code it seems to correct the stereo width.  Why correct it first and then mess with the MS afterwards?

**Comment by magnetophon** [comment]
> With the colors, I am not quite sure yet.

I prefer the colors that @falkTX chose [here](https://user-images.githubusercontent.com/1334853/185085001-de37e774-be79-4469-b5d5-ee63fdb91e54.png).

**Comment by trummerschlunk** [comment]
> A more general question: it seems to me the DSP is not finished yet; you still need to decide wich blocks will be in the final product, and which parameters of wich blocks are exposed (for example, I would expose the knee parameter of all compressors and limiters.
> 
> Finally, also related to how the gui will look, sice it depicts the flow: shouldn't the correlation correction be after all the MS processing? Maybe I misunderstood what it's supposed to do, but from the name and a quick glance at the code it seems to correct the stereo width. Why correct it first and then mess with the MS afterwards?

almost finished ;)

the correlation correction is a feature request from the ccc voc team. If a signal is mono, but not in the middle, it is put in the middle. This comes from some situations, where people will stream with two mics, not putting them both in the middle, but left and right.

**Comment by trummerschlunk** [comment]
> > With the colors, I am not quite sure yet.
> 
> I prefer the colors that @falkTX chose [here](https://user-images.githubusercontent.com/1334853/185085001-de37e774-be79-4469-b5d5-ee63fdb91e54.png).

I like it too... A bit too 'native-instruments', maybe?
This is probably an easy tweak in the end...

**Comment by trummerschlunk** [comment]
![soundsgood gui sketch expert07 excalidraw](https://user-images.githubusercontent.com/19374731/185096598-fad8161e-8b7b-4724-8f46-a4422a6254ee.svg)


knee added for 'limiter'
stereo control changed

I am pretty sure, that these are all the parameters and the signal flow is fine.

**Comment by trummerschlunk** [comment]
The only thing I don't know how to solve: the ms-multiband-comp gain reduction meters have no numeric readout yet. And we need it.

**Comment by trummerschlunk** [comment]
@falkTX All this exercise is more about coming clean with the final parameters and signal flow. If you have other ideas, go for it!

**Comment by trummerschlunk** [comment]
<img width="121" alt="image" src="https://user-images.githubusercontent.com/19374731/185105930-1a4d6acc-52fb-4986-912b-cb326e726373.png">

I really like the intuitive aspect of this. If input-lufs, target, output lufs have the same scale.
Maybe it's better than my previous 'big-meters'. I just don't know where to put the labels...

**Comment by magnetophon** [comment]
> knee added for 'limiter'

Why not expose the knee for the brickwall as well?

Also, since the limiter has a strength parameter, it stops being a limiter and becomes a compressor, right?
Since all compressors have knee, and all compressors have MS, those are not that helpful in the name of the block, imho.

I propose the following names:
- pre compressor  (currently knee-comp)
- multiband compressors (currently ms-multiband-compressor)
- post compressor (currently limiter)
- limiter (currently brickwall)

Related issue: [https://github.com/trummerschlunk/soundsgood/issues/25](https://github.com/trummerschlunk/soundsgood/issues/25)

**Comment by magnetophon** [comment]
> The only thing I don't know how to solve: the ms-multiband-comp gain reduction meters have no numeric readout yet. And we need it.

Just add ``[unit:dB]`` and faust will take care of it.  Also for the ``leveler_meter_gain``.

**Comment by trummerschlunk** [comment]
> > The only thing I don't know how to solve: the ms-multiband-comp gain reduction meters have no numeric readout yet. And we need it.
> 
> Just add `[unit:dB]` and faust will take care of it. Also for the `leveler_meter_gain`.

This was meant GUI-wise. No space... ;)

**Comment by x42** [comment]
May I suggest to take inspiration from the Harrison Mixbus master-strip?
In particular the bargraph stereo-correlation meter:
![image](https://user-images.githubusercontent.com/30246/185258051-470455a4-dc19-497e-b5a2-28078c28fe56.png)

Oh, and I do have a faible for needle-meters. Especially is space is limited they're a lot more readable.

**Comment by x42** [comment]
PS. I do like the arrows showing the signal flow!

**Comment by falkTX** [comment]
do the presets need to be there in advanced mode?
the simple/easy mode is lacking things to show if we want to have GUI size the same as the advanced one, so one idea is to have the preset buttons visible only on the easy mode.

**Comment by trummerschlunk** [comment]
not really... I think we can put them in 'simple-mode' only. Then it's kind of a 'preset-mode'.

**Comment by falkTX** [comment]
alright, then easy mode can just have some big noob buttons :D

**Comment by trummerschlunk** [comment]
plus the welcome-text, I'll write soon.
perfect!

**Comment by trummerschlunk** [comment]
closing this in favor of https://github.com/trummerschlunk/soundsgood/issues/40
