### ISSUE TITLE
Expose a few more parameters, increase some ranges.

### ISSUE THREAD

**Issue by magnetophon** [trummerschlunk/master_me#25]
I understand that the main goal is to make more or less subtle corrections to the audio based on presets.

At the same we want to expose te expert interface as well.
It would be nice if that one allows to do heavy corrections or creative sound design.

Finally, I think the plugin would become more intuitive to work with if all similar parameters and displays have the same range.
With a consistent mapping between the visual position of a fader (or meter) and it's meaning you can get used to them quicker and focus on the sound more.

Therefore, I propose the following ranges:
- all GR meters to -24 dB - 0 dB
- all thresholds -24 dB to +24 dB
- all makeup gains -24 dB to +24 dB
- all eq gains -24 dB to +24 dB
- all knee parameters exposed (so every compressor and limiter you choose to include), range -24dB to 0dB
- all attack & release 0 to 1000 ms, log scale (IIUC a log scale cannot start at 0, so in reality ths needs to be a 'faked' log scale)
- hp freq 0 to 1000 Hz, 'faked' log scale.
- all eq freqs 20 Hz to 20 kHz
- all comp strengths 0 to 8, ideally with 1 being the middle.
- make each dynamics block have the option of MS or stereo.

**Comment by trummerschlunk** [comment]
I hear you.
unifying similar parameters is good. I will look into it.

But I disagree with exactly copying all features of the faust modules to the gui. Next to the leveler, a key part of the project is to model the mastering chain from my studio which I formed in almost 20 years of experience. Some parameters of the used faust functions can do more - sure, but they don't correspond to my chain and workflow.

**Comment by magnetophon** [comment]
> a key part of the project is to model the mastering chain from my studio which I formed in almost 20 years of experience

Totally agreed, for the presets we should rely on your experience, but in most cases, I don't see much value in hard coding stuff in the expert interface; that's what the presets are for, no?

There are exceptions to this, for example the attack and strength of the final limiter should be hardcoded.
There might be other examples.

I think the ranges should be as big as possible, but not so big that you have too little fine control in the important range.

In the end it's your choice, of course.

**Comment by trummerschlunk** [comment]
I see the chain as a preset itself. And ranges matter a lot. I want to make it easier for users to stay in 'tested' areas.

But I'll look into the parameters.

Thank you!
