### ISSUE TITLE
dsp code TODOs

### ISSUE THREAD

**Issue by trummerschlunk** [trummerschlunk/master_me#29]
- [x] global bypass
- [x] leveler: try expander instead of gate for silence detection
- [x] leveler: fix wrong calculation

- [x] side-eq: try different shelf eqs

- [x] kneecomp: drywet control (after makeup)
- [x] kneecomp: feedforward/feedback control
- [x] limiter: try different limiters available in faust

**Comment by x42** [comment]
* [x] ms-compressor: fix phase smearing #26

**Comment by magnetophon** [comment]
kneecomp dry wet and some issues with https://github.com/trummerschlunk/soundsgood/issues/26 are fixed in https://github.com/trummerschlunk/soundsgood/pull/38
