### ISSUE TITLE
Loudness filter fixed for 48kHz

### ISSUE THREAD

**Issue by jkbd** [trummerschlunk/master_me#3]
I think, the LUFS filter is only correct for a samplerate of 48kHz.
Should this be doing EBU-R128 prefiltering? Like the ITU filter in [Loudness Measurement according to EBU-R128 (page 13)](http://kokkinizita.linuxaudio.org/papers/loudness-meter-pres.pdf)? If yes, I have some code in my sleeve.

**Comment by trummerschlunk** [comment]
Yes, you are right - that would be extremely helpful.
