### ISSUE TITLE
Project Title

### ISSUE THREAD

**Issue by trummerschlunk** [trummerschlunk/master_me#32]
Dear all,

I have been wrapping my head around this for quite some time now.
I kind of like 'soundsgood' as the name for a tool you throw at the master and hopefully then it 'soundsgood'.

I also like master_me as the project from which this one came...

So. If you have any other ideas for naming this beast, please share - thank you!

**Comment by falkTX** [comment]
One big issue with "soundsgood" is that it starts with a verb.
On a casual conversation one would say something like "checkout this new plugin, it is soundsgood", which does not sound good, sounds weird instead..
A quick (perhaps silly) new name is to just swap the 2 words to "goodsound".
So on a casual conversation like above it would be "checkout this new plugin, it is goodsound".

but better ask a native english speaker

**Comment by x42** [comment]
I still kinda like "soundd**EBU**t"  which lead to "sounddeputy". 

some random brainstorming:
* Lowi (loudness wizard)
* saustak (sounds stark[de])
* nachklang
* sonoribus
* loudpeace -- the end of the loudness war :)
* audio clarifier
* quiesverter - silence [con]verter.
* klangverter
* klangspatz
* klangfinale
* mixprimo
* soundshine
* loudness ranger
* loudness dentist (https://xkcd.com/2656/)

**Comment by trummerschlunk** [comment]
klangspatz <3
;)
Thank you, Robin!

**Comment by x42** [comment]
A recursive acronym would be cool. 

also "soundsgood" is a fine name, except nobody will find it when searching the web.

**Comment by trummerschlunk** [comment]
Thank you all, there are some really nice and funny ideas :)
In the end, I decided to go with the original name, which is public for quite some time.

Welcome (back): master_me

:)
