### ISSUE TITLE
Missing parameter units

### ISSUE THREAD

**Issue by falkTX** [trummerschlunk/master_me#36]
A few parameters do not have units, this ticket serves to track down these and possibly make a decision on them.

Switches (including bypass) do not need them.
But others should have them, if possible.

(Personally I find 0-100% more readable than 0.0-1.0 raw values)

Current parameters without unit:

- [ ] leveler gain (passive)
- [ ] leveler gate (passive)
- [ ] gate attack
- [ ] gate hold
- [ ] gate release
- [ ] leveler speed
- [ ] leveler max+
- [ ] leveler max-
- [ ] eq tilt gain typo (db vs dB)
- [ ] eq side gain typo (db vs dB)
- [ ] eq side bandwidth
- [ ] kneecomp strength
- [ ] kneecomp knee
- [ ] kneecomp link
- [ ] kneecomp fffb
- [ ] kneecomp drywet
- [ ] everything in mscomp except output gain (active)
- [ ] limiter strength
- [ ] limiter attack
- [ ] limiter release
- [ ] limiter fffb
- [ ] limiter knee

**Comment by falkTX** [comment]
Aside from the obvious typos of db vs dB, there are a few other things which seem clear. Please comment if correct or wrong, thanks.

1. pre-processing input gain should be dB
2. all attack, hold and release parameters should be milliseconds (since knee compressor has attack and release as milliseconds)
3. all knee parameters should be dB (only limiter has it set at the moment)
4. leveler max+ and max- should be dB
5. knee compressor dry/wet should be %
6. mscomp crossover should be Hz
7. mscomp tar-threshold should be dB (then matching others)
8. mscomp output gain should be dB

**Comment by trummerschlunk** [comment]
yes to all :)

**Comment by trummerschlunk** [comment]
most 0.x parameters should be 0-100%

**Comment by trummerschlunk** [comment]
all done
