### ISSUE TITLE
GUI related issues and ideas

### ISSUE THREAD

**Issue by trummerschlunk** [trummerschlunk/master_me#40]
- [x] target fader needs some label 'target'
- [x] mb-ms-comp: name needs multiband reference. Let's make it 'Multiband MidSide Comp'. Hope it fits.
- [x] mb-ms-comp: numeric readout or scale on the meters.
- [x] mb-ms-comp: rename 'output-gain' to 'makeup'
- [x] mb-ms-comp: put 'low' and 'high' below the paramters, so parameters are in horizontal line with kneecomp and limiter.
- [x] all: separator before meters without 'Outputs:'
- [x] 'enable' left of pluginname?
- [x] change plugin name to 'master_me'
- [x] gate meter missing

**Comment by falkTX** [comment]
>  mb-ms-comp: name needs multiband reference. Let's make it 'Multiband MidSide Comp'. Hope it fits.

> mb-ms-comp: put 'low' and 'high' below the paramters, so parameters are in horizontal line with kneecomp and limiter.

these 2 are done, please check latest build

>  mb-ms-comp: rename 'output-gain' to 'makeup'

should be done on faust dsp file side, you should be able to change and try it out

**Comment by trummerschlunk** [comment]
- [ ] gate meter missing

**Comment by falkTX** [comment]
please update the first post for adding new items.

**Comment by falkTX** [comment]
> * target fader needs some label 'target'

> * all: separator before meters without 'Outputs:'

> * change plugin name to 'master_me'

these should be done with d833f8474293cf636013cee50d7f6eafae9b4602

on the mscomp meter labels, not sure where to place those, suggestions welcome.
perhaps using the right-side space for it?

**Comment by falkTX** [comment]
> * gate meter missing

what meter is this? I dont see it exported.. maybe the "leveler_gate" one is misplaced?

**Comment by trummerschlunk** [comment]
> > * gate meter missing
> 
> what meter is this? I dont see it exported.. maybe the "leveler_gate" one is misplaced?

dammit, it has none... I will investi-gate, harr harr

**Comment by trummerschlunk** [comment]
multiband midside compressor:
the meters are in the wrong order.
lowest frequency should be on the left.

**Comment by trummerschlunk** [comment]
> on the mscomp meter labels, not sure where to place those, suggestions welcome. perhaps using the right-side space for it?

we could place 'brickwall' under 'limiter', make 'mb-ms-comp' wider and place numeric readout in the meters, which could then be wider.

**Comment by falkTX** [comment]
> > on the mscomp meter labels, not sure where to place those, suggestions welcome. perhaps using the right-side space for it?
> 
> we could place 'brickwall' under 'limiter', make 'mb-ms-comp' wider and place numeric readout in the meters, which could then be wider.

that was my intention, specially considering the still missing arrows

**Comment by trummerschlunk** [comment]
Good!
Maybe not even arrows but 'connections'.
Just a straight line, connecting the modules?

**Comment by falkTX** [comment]
how would we indicate the flow with a single line?

testing arrows.

![image](https://user-images.githubusercontent.com/1334853/186359277-5edb7d29-eb2f-4910-a329-5e9a96df690a.png)

too silly?

**Comment by magnetophon** [comment]
I just noticed that the EQ is in fact between the knee compressor and the MB comp.
So unless we want to change the GUI layout or change the DSP, it might be better to leave out the arrows, as they might be confusing otherwise.

**Comment by trummerschlunk** [comment]
> how would we indicate the flow with a single line?
> 
> testing arrows.
> 
> ![image](https://user-images.githubusercontent.com/1334853/186359277-5edb7d29-eb2f-4910-a329-5e9a96df690a.png)
> 
> too silly?

maybe a bit smaller, darker?

**Comment by trummerschlunk** [comment]
> I just noticed that the EQ is in fact between the knee compressor and the MB comp. So unless we want to change the GUI layout or change the DSP, it might be better to leave out the arrows, as they might be confusing otherwise.

my bad. EQ section is before the kneecomp.

**Comment by falkTX** [comment]
is anything incorrect on the UI positioning?

**Comment by trummerschlunk** [comment]
no, all correct

**Comment by trummerschlunk** [comment]
dammit, I am so sorry, @falkTX 
The EQ-module needs to be before the leveler.
thanks @magnetophon for pointing me in this direction.

**Comment by falkTX** [comment]
ah just swapping the 2 then. quite ok to do.

**Comment by falkTX** [comment]
so this is correct now?

![image](https://user-images.githubusercontent.com/1334853/186520451-04cb9141-e958-423c-9926-94258d3e4df0.png)

just needs the gate meter

**Comment by trummerschlunk** [comment]
yes.
two more arrows?
![image](https://user-images.githubusercontent.com/19374731/186591551-9641a0ee-6c4c-47b6-82c4-ca48d5de7a70.png)

**Comment by trummerschlunk** [comment]
ah, you did them already :)

**Comment by x42** [comment]
Maybe align the bottom row to the right? 

Anyway, each of the sub-parts having a different width and height looks rather weird to my eye. Are the plans to clean this up?

**Comment by falkTX** [comment]
> Anyway, each of the sub-parts having a different width and height looks rather weird to my eye. Are the plans to clean this up?

Got any ideas.
If you run the latest build you can click on the plugin name to open the theme editor which has a widget list with some properties below it, allowing us to fiddle with position and sizes.

Making everything have the same height doesnt look to me tbh, tried it just now:

![image](https://user-images.githubusercontent.com/1334853/186791424-f35e46ba-4dc6-4e4b-9a3a-365829c4d260.png)

We could vertically align the groups perhaps?

**Comment by falkTX** [comment]
>     * mb-ms-comp: numeric readout or scale on the meters.

does this work?

![image](https://user-images.githubusercontent.com/1334853/186797273-81fa70c0-77e3-4225-b01d-31e3697f886d.png)

**Comment by falkTX** [comment]
or maybe the other way around. from -3 in the center to 0 on the edges?

![image](https://user-images.githubusercontent.com/1334853/186797515-b88ca386-479e-4dcb-bd1c-7ad3b44eac03.png)

**Comment by trummerschlunk** [comment]
> or maybe the other way around. from -3 in the center to 0 on the edges?


I really like this last one!
But labels need to be swapped. 0dB in the middle and -3dB top and bottom.

Also, I think we can drop the numbers above the bands. Saving one row of space.

**Comment by trummerschlunk** [comment]
The gate meter becomes all black, when it reaches -70dB, when it should be all yellow.

**Comment by falkTX** [comment]
> > or maybe the other way around. from -3 in the center to 0 on the edges?
> 
> I really like this last one! But labels need to be swapped. 0dB in the middle and -3dB top and bottom.

if we make -3db on top and bottom and 0db in the middle, we cant really use the same style of metering where it flows from the middle to the edges, because typically these meters are in -3dB and slowly grow into 0dB. which means their meters flow from the edges into the middle.

**Comment by falkTX** [comment]
wait no, I am wrong. 0dB is the default and it slowly goes till -3dB.
seems same issue as with the gate meter

**Comment by falkTX** [comment]
> The gate meter becomes all black, when it reaches -70dB, when it should be all yellow.

fixed now too, along with the rest on this ticket.

please check and confirm (closing ticket if all good)
