### ISSUE TITLE
VST3 - messed up GUI

### ISSUE THREAD

**Issue by trummerschlunk** [trummerschlunk/master_me#47]
![image](https://user-images.githubusercontent.com/19374731/186605858-5383c241-83ee-4f0c-8403-5b7e1918d039.png)

**Comment by falkTX** [comment]
other info: this is reaper on macOS.

reaper tends to force vst3 UIs to the minimum size.
other dpf based plugins have the same issue, though with the ui being set as fixed-size this shouldn't happen.

**Comment by trummerschlunk** [comment]
ok, thanks. Can I close this?

**Comment by falkTX** [comment]
bug is not fixed yet, so no :)

**Comment by falkTX** [comment]
fixed in a2af773acfeef32d8aadcfe21040a68605c36506

**Comment by trummerschlunk** [comment]
nice!
