### ISSUE TITLE
all integer value sliders have strange behavior when dragging vertically

### ISSUE THREAD

**Issue by trummerschlunk** [trummerschlunk/master_me#48]

**Comment by falkTX** [comment]
this seems related to them being in integer steps, something wrong from dpf event handling side.
applies to value sliders that use % as unit, as well as the target slider, all of them are stepped by 1.f values, basically integer sliders.

**Comment by falkTX** [comment]
Should be fixed in b0af013d9dc23a785e4e5c61ddc81dfa0bf2c6a6

**Comment by trummerschlunk** [comment]
seems to work fine in the 'upward' direction ( making a value bigger), but not 'downward' making it smaller

**Comment by falkTX** [comment]
how so? is it different now?

**Comment by trummerschlunk** [comment]
https://user-images.githubusercontent.com/19374731/187062662-a30dfc19-7381-44c6-a9ef-8954ce9c0e4a.mov

**Comment by trummerschlunk** [comment]
on vst, vst3, macOS, highdpi this is not solved, yet.

**Comment by falkTX** [comment]
I was able to reproduce, should now be fixed in 9409e0a0152115ff2892a236bf4c86c26ab029bd

**Comment by trummerschlunk** [comment]
great, done!
