### ISSUE TITLE
Oddities with leveler gate meter values

### ISSUE THREAD

**Issue by falkTX** [trummerschlunk/master_me#52]
The leveler gate meter has % unit, but range of 0 to 1.
Plus minimum value only seems to ever each 0.143, which is weird

Currently looks wrong on the gui too, as it does not behave like all the other meters.
For this one we want the meter to go from left to right, correct? (ie, from 0 to 100%..?)

**Comment by falkTX** [comment]
@trummerschlunk is the leveler gate meter (on the gui) now ok, or should it work the other way around?

**Comment by trummerschlunk** [comment]
Ah, I see. It should be black  when 0% and go from (black) left to right (colored).

**Comment by falkTX** [comment]
Should be fixed in 4f645cc4bd6c1b38a5b4dcee622ca827a028b15b

**Comment by trummerschlunk** [comment]
nice!
