### ISSUE TITLE
Make target slider -2dB max

### ISSUE THREAD

**Issue by falkTX** [trummerschlunk/master_me#53]
As previously discussed.

Ticket serves as reminder and to check on progress on the task. Which as of now is still TODO.

**Comment by falkTX** [comment]
@trummerschlunk is this done on dsp side yet?

**Comment by trummerschlunk** [comment]
as of now :)

**Comment by falkTX** [comment]
dont close, now I have to handle the ui side for this too

**Comment by falkTX** [comment]
Fixed in 0eeb741943c814eb8ecdb07dab6f7b642434f6b4
