### ISSUE TITLE
align logo to right side of output meters

### ISSUE THREAD

**Issue by trummerschlunk** [trummerschlunk/master_me#54]
please align the logo to the right side of output meters
<img width="391" alt="image" src="https://user-images.githubusercontent.com/19374731/187018616-9e9b20fa-03a3-4a23-b02a-1a39abfced4d.png">

**Comment by magnetophon** [comment]
We have a logo now!  :)
Looks great, who made it?

**Comment by trummerschlunk** [comment]
@petrio
https://github.com/petrio
<3

**Comment by falkTX** [comment]
Should be done in 908dd9475557e8cc1c80aef6be03853e44ac59be, please confirm

**Comment by trummerschlunk** [comment]
sweet!
