### ISSUE TITLE
slider double-click

### ISSUE THREAD

**Issue by falkTX** [trummerschlunk/master_me#57]
A ticket to discuss the double-click text input topic in particular.

Few things to do:
- [x] make font size match theme one
- [x] make highlight color match current slider background color?
- [x] ensure no right-click menus can be used (would go into imgui widgets, which dont match plugin ones)

after those are done, we will need testing.

**Comment by trummerschlunk** [comment]
looking good to me.
background color for double-clicked values is fixed now? I guess it should be the slider's color, right?

**Comment by trummerschlunk** [comment]
this seems to work fine now, right?

**Comment by falkTX** [comment]
yes, I just want to match the styling now

**Comment by falkTX** [comment]
fixed in 0710a71f522fb85bec45d023525b1f34550daa14
