### ISSUE TITLE
Dealing with keyboard input on plugin hosts

### ISSUE THREAD

**Issue by falkTX** [trummerschlunk/master_me#59]
Reaper by default does not give plugin UIs keyboard focus, which makes it super easy to press backspace and have it delete the plugin 😡 

It is the same issue as dealt in https://github.com/DISTRHO/Cardinal/issues/304
We need the same hacks here too, likely best pushed as direct DPF functionality.

**Comment by trummerschlunk** [comment]
lots of plugins have this issue in reaper. (Voxengo,...)

**Comment by falkTX** [comment]
the workaround I found that works the best is to force keyboard focus to the plugin UI whenever a user clicks on it.
it is super ugly, but nothing else I tried was working proper.

**Comment by trummerschlunk** [comment]
ok, then this is the way to go...

**Comment by falkTX** [comment]
bruteforce activated in 7b2948c8a4c83cfdb767b0b101873ecbfa5c74f2
