### ISSUE TITLE
error building under macOS 11 with homebrew faust

### ISSUE THREAD

**Issue by falkTX** [trummerschlunk/master_me#6]
Getting this error on macOS 11, for the CI automated build:

```
ERROR : path '/soundsgood/expert/mscomp_meter/1' is already used
```

any hints?

issue does not happen on macOS 12 or on Linux, so perhaps a faust side issue?

**Comment by trummerschlunk** [comment]
I just pushed a new version with labeling of the mscomp meters disabled. Dos it work for you now?

**Comment by falkTX** [comment]
let's check,we can see the updated build in https://github.com/trummerschlunk/soundsgood/runs/7807671979?check_suite_focus=true

**Comment by falkTX** [comment]
yeah, it builds fine now!
