### ISSUE TITLE
make presets save 'easy' or 'expert' state

### ISSUE THREAD

**Issue by trummerschlunk** [trummerschlunk/master_me#65]
make presets safe 'easy' or 'expert' state

**Comment by trummerschlunk** [comment]
plugin always opens in 'easy' mode, when reopened in DAW
it should remember the last used page
this is probably related?

**Comment by falkTX** [comment]
that state is already saved, have to check how it is not being recalled.
what plugin format you are testing?

**Comment by trummerschlunk** [comment]
vst on macOS 12.5
reaper

**Comment by falkTX** [comment]
just fixed this, confirm with the latest builds please.

**Comment by trummerschlunk** [comment]
works!

**Comment by SimpelMe** [comment]
The easy/expert state isn't recalled (or safed) correctly for au plugin on macOS 13.6.3 in reaper.
