### ISSUE TITLE
GUI: easy page layout

### ISSUE THREAD

**Issue by trummerschlunk** [trummerschlunk/master_me#68]
trying some layouts for 'easy' page. I like the second one better...

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/19374731/187134296-f0c0b9f5-f2cd-4b9c-80a5-aceaa2774cf6.png">

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/19374731/187134624-444019c1-603b-4a04-9103-f623fdacdd7d.png">

**Comment by falkTX** [comment]
an alternative is placing the histogram labels on the top, so it more nicely fits in the middle position.
and then the easy presets going in the bottom, probably stretched out so it fits the whole width.

**Comment by trummerschlunk** [comment]
yeah, cool, let's try!

**Comment by trummerschlunk** [comment]
Please add @jkbd to the contributors :)

**Comment by falkTX** [comment]
here we go

![image](https://user-images.githubusercontent.com/1334853/187188767-7e4bd196-e4b4-4799-ba89-1ecdcbf3a56f.png)

**Comment by falkTX** [comment]
is the intention to reduce to frame size to not include histogram and presets? will look a bit off when switching modes

**Comment by trummerschlunk** [comment]
the last one looks great to me :)

**Comment by falkTX** [comment]
so do we consider this one done?

**Comment by trummerschlunk** [comment]
Yes. Texts will change slightly. See https://github.com/trummerschlunk/master_me/issues/71
