### ISSUE TITLE
preset buttons need to go black again after loading, or changing a parameter

### ISSUE THREAD

**Issue by trummerschlunk** [trummerschlunk/master_me#70]
preset buttons need to go black again after loading, or changing a parameter

**Comment by falkTX** [comment]
we can always have them go a color in between to show current values are based on a preset, but that is a bit hard to define.

I had this same idea too btw, the ticket for the presets mentions this (as mid-prio as well)

**Comment by falkTX** [comment]
Done in efb4f1df2ea06bd7d07251401881884105718dee, please check

**Comment by trummerschlunk** [comment]
done, thanks!
