### ISSUE TITLE
Texts for 'Easy' page

### ISSUE THREAD

**Issue by trummerschlunk** [trummerschlunk/master_me#71]
**These are the texts for 'Easy' page:**

Hi there,

master_me is a free and open source automatic mastering plugin for live streamers, podcasters and internet radio stations.

You are currently in “Easy” mode.
Select a preset from the bottom and forget about it.

Choose “Expert” mode to see and tweak what's under the hood.

Happy streaming!

**And on the right side:**

master_me
A plugin by Klaus Scheuermann.
With contributions from falkTX, jkbd, magnetophon, x42 and others.
Made with Faust and DPF.
Supported by the Prototype Fund / German Federal Ministry of Education and Research.

**Comment by falkTX** [comment]
tweaked in 8f50e6402aa846851ce457cde825fc1a38c5b5d7

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/1334853/187322832-cae41df2-b113-49eb-a6a6-b6ee36a4bfc1.png">

**Comment by falkTX** [comment]
A little suggestion, merging "a plugin by" with "made with faust and dpf", so it would be:

> master_me
> A plugin by Klaus Scheuermann, made with Faust and DPF.
> With contributions from falkTX, jkbd, magnetophon, x42 and others.
> Supported by the Prototype Fund / German Federal Ministry of Education and Research.

**Comment by falkTX** [comment]
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/1334853/187323184-b7646682-c101-4f46-a8d8-45ab5601d676.png">

**Comment by falkTX** [comment]
after seeing it, I dont like it anymore :P

**Comment by trummerschlunk** [comment]
Final texts for Easy-Page:

Hi there,

master_me is a free and open-source automatic mastering plugin for
live streamers, podcasters, and internet radio stations.

You are currently in “Easy” mode.
Select a preset from the bottom and let master_me take care of the rest.

Choose “Expert” mode to see and tweak what's under the hood.

Happy streaming!

A plugin by Klaus Scheuermann, made with Faust and DPF.
DSP: Klaus Scheuermann, magnetophon, x42, jkbd
GUI, Plugin: falkTX
Supported by the Prototype Fund / German Federal Ministry of Education and Research

**Comment by falkTX** [comment]
has been updated.
reduced the spacing between credits and build info, make the build info light text color, but dont like it myself

![image](https://user-images.githubusercontent.com/1334853/187406537-e14dd94b-82c3-47e4-b30d-7ae8bef382d6.png)

what do you think?
and the build info text, perhaps I revert back to the same color

**Comment by trummerschlunk** [comment]
do we need the build text?

**Comment by falkTX** [comment]
not exactly, but it helps a lot for visually seeing what version the user is running.
when something goes wrong, it is crucial to know the version.

we could switch to that, (number) version. but I am not sure where to place that.. on top of the credits? like so?:

> master me v1.0
> A plugin by ...

**Comment by trummerschlunk** [comment]
I would put it on the expert page
bottom right
maybe only the build number?

**Comment by falkTX** [comment]
Is it really that ugly?
Trying it now it nicely fits below the brickwall

![image](https://user-images.githubusercontent.com/1334853/187411034-94867f47-0b32-4b5c-905c-6590e30e4d98.png)

**Comment by trummerschlunk** [comment]
it's not ugly ;)
just thought it might be distracting for 'Easy' users.
Like this it's pretty!

**Comment by falkTX** [comment]
I like it this way too. Would leave it like that then.

**Comment by x42** [comment]
It's the first thing I add to every plugin UI. It is invaluable to always have the Version number visible for Bug reports.
2c

**Comment by trummerschlunk** [comment]
ok :)
