### ISSUE TITLE
crash in reaper, when deleting one of two master_me instances on one track

### ISSUE THREAD

**Issue by trummerschlunk** [trummerschlunk/master_me#78]
reaper crashes on macOS when:
I load two instances of master_me on one track and then remove one instance.

**Comment by falkTX** [comment]
what plugin format were you using?

**Comment by trummerschlunk** [comment]
this happens with vst
vst3 works fine

**Comment by trummerschlunk** [comment]
just tried it on arch linux reaper. Same.

**Comment by falkTX** [comment]
Should be fixed with 30b8c08c4b99a5fc95cdcc3320baf28761e81dfc

With the last round of fixes I think it is time to do a v1.1.0 update

**Comment by falkTX** [comment]
The same issue was happening in https://github.com/DISTRHO/Cardinal/issues/273 and has been confirmed to be fixed now

**Comment by trummerschlunk** [comment]
fix confirmed!
