### ISSUE TITLE
avoid sqrt() calls in inner loop DSP for mid/side calc

### ISSUE THREAD

**Issue by x42** [trummerschlunk/master_me#8]
https://github.com/trummerschlunk/soundsgood/blob/e8eb9ba756971c22c5da8ca5a1f887f9f342faac/soundsgood.dsp#L395

One usually uses a factor or 0.5  when converting left/right to mid/side  and then just sums for the inverse
```
mid = 0.5 * (left + right)
side = 0.5 * (left - right)
```
and then
```
left = mid + side
right  = mid -side
```

As opposed to the sqrt() approach, this also ensure that the mid value will not exceed 1.0, if both source values are below 1.0.

Note multiply by 0.5, which is faster than diving by two (although some compilers change this with fast-math)

**Comment by trummerschlunk** [comment]
This is the way I knew and did it before. I just found jkbd's way of putting the encoder and decoder in one combined function very elegant ;) Will revert to the 'old' way.
Thanks a lot!

**Comment by trummerschlunk** [comment]
// stereo to m/s encoder
ms_enc = _*0.5,_*0.5 <: +, -;
// m/s to stereo decoder
ms_dec = _,_ <: +, -;
