### ISSUE TITLE
GUI: LV2 macOS version small size on high-dpi

### ISSUE THREAD

**Issue by trummerschlunk** [trummerschlunk/master_me#83]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/19374731/187879371-edd63de7-8a61-4593-b1f4-f73f20808322.png">

**Comment by falkTX** [comment]
ardour and high-dpi is a bit of a problem, they report "1.0" as the scale factor for plugins to use, and so dpf follows that.

**Comment by falkTX** [comment]
note that for macOS vst2 and vst3, dpf ignores the scale factor from the host and gets it directly from the view/window.
from what I could find, this is the approach every other macOS VST plugin has. they all ignore the scale factor hints under macOS.

maybe the same should be done for LV2...

@x42 opinions? this is no longer the weird case of using a TV as screen as I had before

**Comment by x42** [comment]
Leave it to macOS to do the scaling. This is done automatically done behind the scene, and per screen. You can move a window from a LowDPI to a Retina/HiDPI display and the UI is up/downsampled as needed, even partially if the window is in between screens.

In case of GL, the keyword here is `wantsBestResolutionOpenGLSurface`

**Comment by falkTX** [comment]
Yeah that seems to be the best approach here.

But sadly that removes the possibility of the host controlling an extra zoom factor on top of the OS one.
If we make the macOS builds ignore the scale factor info from the host, but read it on other systems, it means the macOS build has less features.

**Comment by x42** [comment]
I don't know about other hosts, but Ardour does not support custom scaling on macOS (inherited from cairo and libfreetype). All UI  and font scaling is left to apple Cocoa/Quartz/CoreFont etc behind the scenes.

**Comment by falkTX** [comment]
Should be fixed by e777255d4d2bfe617a80e753a9853dd5949ec2c4 please confirm

**Comment by trummerschlunk** [comment]
confirmed! Thanks!

**Comment by x42** [comment]
On macOS do nothing, and let Apple do the scaling. That works behind the scene and is per screen
