### ISSUE TITLE
gui : no vumeter on vst2 and vst3 on windows10 64 bits

### ISSUE THREAD

**Issue by garfieldthebest** [trummerschlunk/master_me#84]
hi , i have no vumeter on vst2 and vst3 on windows10 64 bits on different vst hoster . However the standalone version is correct  with the gui.

![masterme](https://user-images.githubusercontent.com/90079611/187972079-b007adad-700a-4e80-9084-acf899e23221.jpg)

**Comment by falkTX** [comment]
huh you have pretty much nothing actually.

what graphics card do you have? are drivers installed?

**Comment by garfieldthebest** [comment]
I have intel hd graphics card . here the standalone : 
![mastermeapp](https://user-images.githubusercontent.com/90079611/187975919-2848162d-6e1e-4a1a-9912-2e67da1178d2.jpg)

**Comment by falkTX** [comment]
err the standalone was not even supposed to be in the installer haha

but maybe this is host specific? try in a few other hosts

**Comment by garfieldthebest** [comment]
yes , i have try too with bluecat patchwork , and i have try on two different pc and same probleme .

**Comment by garfieldthebest** [comment]
i have noticed than in expert mode i have something : 
![masterme2](https://user-images.githubusercontent.com/90079611/187979000-ccf51d38-6d64-46f6-996f-c4667d9b98fb.jpg)

**Comment by falkTX** [comment]
maybe a general windows issue, I did not test the plugin there myself.

let's wait for someone else to possibly chime in and confirm it.

**Comment by garfieldthebest** [comment]
ok , but something seem to be wrong with vst build .

**Comment by garfieldthebest** [comment]
the lv2 plugin seem work fine : 
![mastermelv2](https://user-images.githubusercontent.com/90079611/187998654-c594dc0b-d6b1-49c9-aa79-5b7ff1bdf76b.jpg)

**Comment by falkTX** [comment]
they are based on exactly the same code

maybe related to non-integer desktop scaling perhaps? do you have desktop set to 125% zoom/scale by any chance?

**Comment by garfieldthebest** [comment]
no , i don't use "zoom" function . May be problem with vst3sdk . You use juce for build? If yes can you give me the juce file, i'll try to build on my side the vst plugin.

**Comment by falkTX** [comment]
no juce used, no vst3 sdk either.
source code is here on github, but building it from windows using makefile (as it is setup now) has never been supported by the underlying framework it uses.

**Comment by garfieldthebest** [comment]
ok

**Comment by polarity** [comment]
It´s the same for me in Bitwig 4.3.4 and OBS 28, Windows 10, vst2 and vst3. 
Standalone works fine.
![grafik](https://user-images.githubusercontent.com/147424/188269821-fca7d387-8943-43a0-8a5a-408df62c8fd3.png)

**Comment by garfieldthebest** [comment]
I have try with a more older version of a juce vst host and miracle , it's run . Strange than with newest vst hoster with last sdk and fully updated it doesn't run.

edit : run only with vst2 , not vst3 .

![master_me](https://user-images.githubusercontent.com/90079611/188298033-0632d5a5-6fdd-43e3-bc22-49704594ee51.png)

**Comment by trummerschlunk** [comment]
I just tested on an older windows machine and all seems fine in Reaper...

![screenshot master_me windows](https://user-images.githubusercontent.com/19374731/188469908-53d10109-7ba6-438c-b798-25768b3972d1.PNG)

![screenshot systeminfo](https://user-images.githubusercontent.com/19374731/188470208-93b9d379-7533-406b-840a-5ecfa22802ee.PNG)

**Comment by trummerschlunk** [comment]
But not with Nuendo 8 (same machine)
![screenshot master_me windows nuendo](https://user-images.githubusercontent.com/19374731/188471322-feefea16-1d0f-4e3c-bb97-2c87638aad67.PNG)

**Comment by garfieldthebest** [comment]
yes really stange problem !

**Comment by falkTX** [comment]
potentially fixed in latest builds, direct link: https://github.com/trummerschlunk/master_me/actions/runs/3025979620

feedback appreciated

**Comment by polarity** [comment]
not fixed for me

**Comment by garfieldthebest** [comment]
same than the user  "polarity" , not fixed for me too .

**Comment by falkTX** [comment]
thanks for the testing, can you now try https://github.com/trummerschlunk/master_me/actions/runs/3029447301 ?

I suspect this still won't be it, but in order to reduce variables it is good to test all the things so we can know for sure what was the cause by the end.

**Comment by garfieldthebest** [comment]
@falkTX same , not fixed for me.

**Comment by falkTX** [comment]
ok new attempt, please try the builds from https://github.com/trummerschlunk/master_me/actions/runs/3032232340

**Comment by polarity** [comment]
it changed into a complete black window (clap & vst3)
![grafik](https://user-images.githubusercontent.com/147424/189557318-c84ee591-f0cd-4fc4-a5d1-105d2d861509.png)

**Comment by falkTX** [comment]
huh that is curious.. if you click around the top-right area a few times, does the theme editor show up?

**Comment by polarity** [comment]
no the gui is completly dead. i can get audio thru but the gui doesnt show up no matter where and how often i click. theres also no resize of the window to force a redraw or something

**Comment by falkTX** [comment]
ok so with https://github.com/trummerschlunk/master_me/actions/runs/3034146611 the ui is resizable, though only in vst3, maybe in clap but didnt test this, best to go with vst3

**Comment by falkTX** [comment]
I mean, with ui resizable we can force a repaint/redraw, to see if that is the issue

**Comment by garfieldthebest** [comment]
same here , black screen.

**Comment by falkTX** [comment]
try to resize the gui from the host side then. we are checking here if triggering a resize and repaint fixes things or not

**Comment by garfieldthebest** [comment]
seem than size of master_me is "static" , i can't make a rezize on my side  .Still black screen with last build.
![master_me2](https://user-images.githubusercontent.com/90079611/189628158-368445c8-18c2-45e9-a966-2d4d38dd59bf.png)

**Comment by falkTX** [comment]
support depends on the host. try one where it failed before and allows resizing

**Comment by garfieldthebest** [comment]
i have try with a others (vsthost and patchwork) with no success , sorry .

**Comment by falkTX** [comment]
you cant resize in those? you are using the vst3 version right?

**Comment by garfieldthebest** [comment]
right.i use vst3.

**Comment by garfieldthebest** [comment]
Hi ,  i have try vst3 (64bits) in ddmf metaplugin who allow resizing , and oh surprise ; when i have redraw master_me , the gui is showing !!! 
![master_me3](https://user-images.githubusercontent.com/90079611/189941522-4b063294-bddf-436d-a5ca-4c9977791e45.png)

**Comment by falkTX** [comment]
I was able to reproduce the issue.
Should be fixed latest builds starting with https://github.com/trummerschlunk/master_me/actions/runs/3048058650

**Comment by trummerschlunk** [comment]
I don't have access to a windows machine at the moment.
@garfieldthebest & @polarity can you confirm?

**Comment by garfieldthebest** [comment]
Hi @trummerschlunk , yes , gui seem working good now with last build , a great thank you . 

However, I have noticed a high cpu usage .

**Comment by trummerschlunk** [comment]
Great. Thanks go to @falkTX :)

Yes, cpu usage still is quite high. We are trying to figure out some optimizations. Hopefully, we will get to a point where master_me runs less hungry...
https://github.com/trummerschlunk/master_me/issues/66

**Comment by falkTX** [comment]
Forgot to close this issue before, doing that now. Thanks for testing!

**Comment by polarity** [comment]
can confirm, works for me too now. thanks for fixing!

**Comment by rafaelholeva** [comment]
Hello, I use OBS Studio in its version 27.2.4 (x64) with the latest version of the plugin vst2 master-me (x64) 1.1.0 and also the GUI (vumeter) is not displayed correctly. Also, there is no animation of the levels in VU meter while the audio is played in OBS STUDIO. I hope this resolves itself, as other plugins are working correctly.
Congratulations on the project, I hope that in the future there will be a standalone version to run on windows compatible with ASIO DRIVER and WASAPI and Wave, DirectSound
