### ISSUE TITLE
[SUGGESTION] restore_me and possible collaborations

### ISSUE THREAD

**Issue by MarcoRavich** [trummerschlunk/master_me#88]
Hi there,
1st of all thanks for your cool work.

We don't know if this falls into the project' scope (anyway, as the title suggests, it could be a part of derivation one), but it would be useful to expand the software's functionalities to audio restoration field too.

There are some interesting open projects that we collected about this (and not only) to evaluate:
[HyMPS](https://github.com/forart/HyMPS) \ [Audio Tools](https://github.com/forart/HyMPS/blob/main/A_Tools.md) \ [Restoring](https://github.com/forart/HyMPS/blob/main/A_Tools.md#restoring-)

We've doxed your - and other mastering - project too (under [Mastering subsection](https://github.com/forart/HyMPS/blob/main/A_Tools.md#mastering-)), of course.

Hope that inspires !

**Comment by MarcoRavich** [comment]
We've reorganized the section and added more interesting stuff:
https://github.com/forart/HyMPS/blob/main/A_Tools.md

Hope that helps !

**Comment by jkbd** [comment]
Thanks for listing all this software. Some is interesting!

In my personal opinion, the count of long-term open issues influences how people estimate the quality of a project. When shall this "issue" be closed?

**Comment by MarcoRavich** [comment]
Well, it should be a @trummerschlunk's decision, to me.

**Comment by trummerschlunk** [comment]
Thanks for doxing master_me, @forart ;)

I could imagine a 'restoration' module for future versions of master_me. An intelligent 'noise reduction' feature or 'voice-focus' feature would be nice. I am always amazed how good such algorithms work in (i)phones. 

The next step is optimizing master_me for cheaper cpu usage though.

Closing this for now - thanks <3

**Comment by MarcoRavich** [comment]
The HyMPs project, at 1st, tries to be a "meeting point" on GH for open source multimedia-ware devs let them (and not only, of course) access other interesting (re)sources and hopefully establish some kind of collaboration with other authors/maintainers.

For example, @HENDRIX-ZT2's [Python Audio Restoration Suite](https://github.com/HENDRIX-ZT2/pyaudiorestoration) has many interesting features as, in a completely different audio-treatment field, @benfmiller's [Audalign](https://github.com/benfmiller/audalign) too.

As said, we also hope devs will help us to make HyMPs more confortable, useful and complete.

Thanks again for the volunteer work you do for the whole community.
