### ISSUE TITLE
Win10 deletes the archive, says it contains a virus

### ISSUE THREAD

**Issue by polarity** [trummerschlunk/master_me#90]
1. download master_me-1.1.0-win64.zip
2. try to unzip it (7zip or winrar)
3. error: archive contains virus
![grafik](https://user-images.githubusercontent.com/147424/192143325-d8a1de02-f554-489f-81dc-0d25a956de22.png)
4. windows deletes the archive

**Comment by falkTX** [comment]
get a better antivirus.

**Comment by polarity** [comment]
i have no anti-virus installed

**Comment by polarity** [comment]
oh closed! see ya

**Comment by falkTX** [comment]
the same thing has been happening for all binaries generated by mingw, it is not an issue, it is a false positive that is seriously annoying by how widespread it is.
