### ISSUE TITLE
Not opening in garageband

### ISSUE THREAD

**Issue by darksideofdonny** [trummerschlunk/master_me#95]
I cannot open the pluggin in garageband. Help! I have a Mac

**Comment by falkTX** [comment]
that is expected, garageband only supports AU

**Comment by darksideofdonny** [comment]
> 

Got it... Any free DAW’s that would work with MasterMe on Mac? I have Audacity lol....

**Comment by trummerschlunk** [comment]
almost free...
reaper.fm <3

free and open source: ardour

**Comment by falkTX** [comment]
audacity supports vst3 plugins now, so that is an option.
