### ISSUE TITLE
libjack64.dll error code 126: the specified module could not be found

### ISSUE THREAD

**Issue by conniebonnie** [trummerschlunk/master_me#99]
when installing I get an error ( failed to create the jack client . communication error with the jack server)

**Comment by falkTX** [comment]
this is not during installing, but when running. use the plugin version instead and ignore the standalone if you dont want to setup jack on windows

**Comment by conniebonnie** [comment]
thank you for the help I got it working

**Comment by JonAnderhub** [comment]
I received the same error message when installing.
What is the fix?
